#!/bin/bash
# Copyright lowRISC contributors (OpenTitan project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
set -e

usage() {
    echo >&2 "ERROR: $1"
    echo >&2 ""
    echo >&2 "Usage: $0 <release-dir>"
    exit 1
}

if [ $# != 1 ]; then
    usage "Unexpected number of arguments"
fi

RELEASE_DIR=$1
if [ ! -d "${RELEASE_DIR}" ]; then
    usage "RELEASE_DIR: ${RELEASE_DIR} does not exist"
fi

CONFIG_DIR="$(dirname "$0")"

source "${CONFIG_DIR}/env/spm.env"

if [ ! -d "${OPENTITAN_VAR_DIR}" ]; then
    echo "Creating config directory: ${OPENTITAN_VAR_DIR}. This requires sudo."
    sudo mkdir -p "${OPENTITAN_VAR_DIR}"
    sudo chown "${USER}" "${OPENTITAN_VAR_DIR}"
fi

echo "Staging envars and configuration files"
cp -r "${CONFIG_DIR}/env" "${OPENTITAN_VAR_DIR}"

mkdir -p "${OPENTITAN_VAR_DIR}/spm/config"
cp -Rf ${CONFIG_DIR}/spm/* "${OPENTITAN_VAR_DIR}/spm/config"

echo "Installing and configuring SoftHSM"

if [ ! -d "${OPENTITAN_VAR_DIR}/softhsm2" ]; then
    mkdir -p "${OPENTITAN_VAR_DIR}/softhsm2"
    tar -xvf "${RELEASE_DIR}/softhsm_dev.tar.xz" \
        --directory "${OPENTITAN_VAR_DIR}/softhsm2"
fi

${CONFIG_DIR}/softhsm/init.sh "${CONFIG_DIR}" \
    "${OPENTITAN_VAR_DIR}/softhsm2/softhsm2" \
    "${OPENTITAN_VAR_DIR}"

echo "Unpacking release binaries"
mkdir -p "${OPENTITAN_VAR_DIR}/release"
tar -xvf "${RELEASE_DIR}/provisioning_appliance_binaries.tar.xz" \
    --directory "${OPENTITAN_VAR_DIR}/release"

# Configure podman to use the local k8s pause container.
mkdir -p ~/.config/containers
cat << EOF > ~/.config/containers/containers.conf
# Configuration autogenerated by deployment script $0
[engine]

infra_image = "podman_pause:latest"

EOF

echo "Loading containers to podman local registry"
podman load \
    -i "${OPENTITAN_VAR_DIR}/release/provisioning_appliance_containers.tar"

echo "Launching containers"
podman play kube "${CONFIG_DIR}/containers/provapp.yml" \
    --configmap "${CONFIG_DIR}/env/spm.yml"
